updating fetch in test reporter

diff --git a/.github/workflows/test_recommendations.yml b/.github/workflows/test_recommendations.yml
--- a/.github/workflows/test_recommendations.yml
+++ b/.github/workflows/test_recommendations.yml
@@ -1,30 +1,66 @@
 name: Determine Tests Bot
 on:
-  pull_request:
-    branches:
-      - main
+  workflow_run:
+    workflows: 
+        - Verify Changes
+    types:
+        - requested
  
 jobs:
   add-comment-to-pr:
     runs-on: ubuntu-latest
     timeout-minutes: 1
+    permissions: write-all
+        
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
  
       - name: Get Recommended Tests
         run: |
-            tests_from_script=$(./.github/scripts/check-changes.sh)
-            echo "rec_tests='Hi, I am a friendly algorithm to help determine which tests you brok - erm, modified. I suggest you run these\n $tests_from_script'" >> $GITHUB_ENV
+            
+            {
+                echo 'tests_from_script<<EOF'
+                ./.github/scripts/check-changes.sh
+                echo EOF
+            } >> "$GITHUB_ENV"
+            
+            echo "rec_tests=Hi, I am a friendly algorithm to help determine which tests you brok.. erm, modified. I suggest you run these! \n" >> $GITHUB_ENV
       - name: Add comment to PR
-        uses: actions/github-script@v7
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            if -n $tests_from_script
-            github.rest.issues.createComment({
-              owner: context.repo.owner,
-              issue_number: context.issue.number,
-              repo: context.repo.repo,
-              body: process.env.rec_tests
-            })
+        
+    #     uses: actions/github-script@v7
+    #     with:
+    #       github-token: {{ secrets.PAT_TOKEN }}
+    #       script: |
+    #         if (process.env.tests_from_script != '') {
+    #             github.rest.issues.createComment({
+    #             owner: context.repo.owner,
+    #             issue_number: context.issue.number,
+    #             repo: context.repo.repo,
+    #             body: "process.env.rec_tests + process.env.tests_from_script"
+    #             })
+    #         }
+        run: |
+            PR_NUMBER=$(jq --raw-output .pull_request.number < $GITHUB_EVENT_PATH)
+
+            response=$(curl -s -o response.json -w "%{http_code}" -X POST \
+                -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }} " \
+                -H "Accept: application/vnd.github.v3+json" \
+                -d '{"body": "'"$rec_tests $tests_from_script"'"}' \
+                "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments")
+
+            if [[ "$response" -lt 200 || "$response" -gt 300 ]]; then
+                echo "Failed to post the comment. HTTP response code: $response"
+                cat response.json
+                exit 1  
+            fi
+
+        #   script: |
+        #     if (process.env.tests_from_script != '') {
+        #         github.rest.issues.createComment({
+        #         owner: context.repo.owner,
+        #         issue_number: context.issue.number,
+        #         repo: context.repo.repo,
+        #         body: process.env.rec_tests + process.env.tests_from_script
+        #         })
+        #     }
