updating git event for workflow_run action

diff --git a/.github/workflows/test_recommendations.yml b/.github/workflows/test_recommendations.yml
--- a/.github/workflows/test_recommendations.yml
+++ b/.github/workflows/test_recommendations.yml
@@ -2,16 +2,17 @@ name: Determine Tests Bot
 on:
   workflow_run:
     workflows: 
-        - Verify Changes
+      - Verify Changes
     types:
-        - requested
+      - requested
+
  
 jobs:
   add-comment-to-pr:
     runs-on: ubuntu-latest
     timeout-minutes: 1
     permissions: write-all
-        
+    if: $(git rev-parse origin/main) != ${{ github.event.workflow_run.head_commit.id }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -21,7 +22,7 @@ jobs:
             
             {
                 echo 'tests_from_script<<EOF'
-                ./.github/scripts/check-changes.sh
+                ./.github/scripts/check-changes.sh "${{ github.event.workflow_run.head_commit.id }}"
                 echo EOF
             } >> "$GITHUB_ENV"
             
@@ -42,21 +43,22 @@ jobs:
     #         }
         run: |
             PR_NUMBER=$(curl -s \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/pulls?state=all" \
-            | jq '.[] | select(.head.sha == "${{ github.event.workflow_run.head_commit_id }}") | .number' | head -n 1)
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              "https://api.github.com/repos/${{ github.repository }}/pulls?state=all" \
+              | jq '.[] | select(.head.sha == "${{ github.event.workflow_run.head_commit.id }}") | .number' | head -n 1)
 
+            if [[ -n "$tests_from_script" ]]; then
+              response=$(curl -s -o response.json -w "%{http_code}" -X POST \
+                  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} " \
+                  -H "Accept: application/vnd.github.v3+json" \
+                  --data-binary '{"body": "'"$rec_tests $tests_from_script"'"}' \
+                  "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments")
 
-            response=$(curl -s -o response.json -w "%{http_code}" -X POST \
-                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} " \
-                -H "Accept: application/vnd.github.v3+json" \
-                -d '{"body": "'"$rec_tests $tests_from_script"'"}' \
-                "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments")
-
-            if [[ "$response" -lt 200 || "$response" -gt 300 ]]; then
-                echo "Failed to post the comment. HTTP response code: $response"
-                cat response.json
-                exit 1  
+              if [[ "$response" -lt 200 || "$response" -gt 300 ]]; then
+                  echo "Failed to post the comment. HTTP response code: $response"
+                  cat response.json
+                  exit 1  
+              fi
             fi
 
         #   script: |
